import React from "react";
import { Info } from "lucide-react";

interface GenericSEOTentProps {
  tool: {
    name: string;
    slug: string;
  };
  category: {
    name: string;
    slug: string;
  };
}

export default function GenericSEOTent({
  tool,
  category,
}: GenericSEOTentProps) {
  const name = tool.name;
  const cat = category.name;

  const faqs = [
    {
      q: `How do I use the ${name}?`,
      a: `Simply type or paste your text into the input field above. The ${name} will automatically transform your characters in real-time. Once satisfied, click the 'Copy' button to use your new text anywhere.`,
    },
    {
      q: `Is the ${name} compatible with Instagram and TikTok?`,
      a: `Yes! The output of our ${name} is standard Unicode, which is natively supported by Instagram, TikTok, Discord, Twitter/X, and almost all other major social platforms.`,
    },
    {
      q: `Does the ${name} work on mobile devices?`,
      a: `Absolutely. Our ${name} is fully responsive and optimized for both iOS and Android browsers, ensuring a smooth transformation experience on any device.`,
    },
    {
      q: `Why does some text look like boxes on my phone?`,
      a: `This is rare and usually only occurs on very old operating systems. 99% of modern devices have full Unicode support for the characters generated by our ${name}.`,
    },
    {
      q: `Can I use ${name} results in my Discord profile?`,
      a: `Yes, you can use the stylized output in your Discord username, status, or channel names. It's a great way to make your profile stand out.`,
    },
    {
      q: `Does the ${name} work offline?`,
      a: "Once the page is loaded, the transformation engine runs entirely in your browser, so it will continue to work even if your internet connection drops. However, you need an initial connection to load the page.",
    },
    {
      q: `What makes this ${name} different from others?`,
      a: `Our ${name} offers the widest selection of ${cat.toLowerCase()} styles powered by an advanced Unicode mapping engine with 7,500+ character mappings. We also provide real-time preview, customization controls, and a privacy-first architecture that competitors lack.`,
    },
    {
      q: `Is ${name} output SEO friendly?`,
      a: `While stylized text looks great, we recommend using it primarily for names, bios, and social media captions. Search engines can still read the underlying characters, but standard text is preferred for large blocks of website content.`,
    },
    {
      q: `Can I clear the input quickly?`,
      a: `Yes, there is a dedicated 'Clear' button next to the input field that allows you to reset the tool instantly for a new generation session.`,
    },
  ];

  return (
    <div className="mt-16 sm:mt-24 max-w-4xl mx-auto space-y-16 px-4 pb-24">
      <div className="space-y-8">
        <div className="p-6 md:p-8 bg-[#0c0c0c] border border-white/5 rounded-2xl relative overflow-hidden">
          <div className="absolute inset-0 opacity-30 pointer-events-none bg-[radial-gradient(circle_at_100%_0%,rgba(57,255,20,0.05)_0%,transparent_50%)]" />
          <div className="relative z-10">
            <h2 className="text-xl md:text-2xl font-black uppercase tracking-tighter mb-4 text-white">
              Maximizing Engagement with{" "}
              <span className="text-accent-glitch">{tool.name}</span>
            </h2>
            <div className="prose prose-invert max-w-none text-white/60 text-sm md:text-base leading-relaxed space-y-4 font-mono">
              <p>
                Built on advanced Unicode algorithms, this generator allows
                users to bypass traditional platform formatting call-to-action
                restrictions. The <strong>{tool.name}</strong> is designed to
                run entirely in your browser through local processing, meaning
                it offers real-time updates and ensures maximum privacy since no
                text data is ever sent to an external server.
              </p>
            </div>
          </div>
        </div>

        <div className="p-6 md:p-8 bg-[#0c0c0c] border border-white/5 rounded-2xl relative overflow-hidden">
          <div className="absolute inset-0 opacity-30 pointer-events-none bg-[radial-gradient(circle_at_0%_100%,rgba(57,255,20,0.05)_0%,transparent_50%)]" />
          <div className="relative z-10">
            <h2 className="text-xl md:text-2xl font-black uppercase tracking-tighter mb-4 text-white">
              Advanced Generation Techniques
            </h2>
            <div className="prose prose-invert max-w-none text-white/60 text-sm md:text-base leading-relaxed space-y-4 font-mono">
              <p>
                To get the most out of our {tool.name}, we recommend
                experimenting with different styles and combinations. Since our
                generator uses advanced Unicode manipulation, the resulting text
                is entirely platform-agnostic. This means you can copy the
                generated output and paste it anywhere—from social media bios
                and captions to gaming chat windows and professional
                profiles—without losing the stylistic formatting.
              </p>
              <p>
                Whether you are optimizing a brand profile, standing out in
                community channels, or simply trying to break out of boring
                standard fonts, this specific effect falls under the{" "}
                <strong>{category.name}</strong> toolkit, widely used globally
                across thousands of social interactions a day. Remember that
                while creative typography significantly boosts engagement,
                readability remains paramount. Use the {tool.name} strategically
                to highlight key phrases and usernames.
              </p>
            </div>
          </div>
        </div>

        <div className="p-6 md:p-8 bg-[#0c0c0c] border border-white/5 rounded-2xl relative overflow-hidden">
          <div className="absolute inset-0 opacity-30 pointer-events-none bg-[radial-gradient(circle_at_100%_0%,rgba(57,255,20,0.05)_0%,transparent_50%)]" />
          <div className="relative z-10">
            <h2 className="text-xl md:text-2xl font-black uppercase tracking-tighter mb-4 text-white">
              Universal Device Compatibility
            </h2>
            <div className="prose prose-invert max-w-none text-white/60 text-sm md:text-base leading-relaxed space-y-4 font-mono">
              <p>
                Unlike external plugins, custom mobile keyboards, or images
                containing stylized typography, the characters produced by the{" "}
                <strong>{tool.name}</strong> exist entirely within the standard
                Unicode specification. This ensures that any string of stylized
                text you create will be natively supported and rendered properly
                across almost all modern digital platforms, from iOS and Android
                devices to Windows and macOS environments.
              </p>
              <p>
                Because this system relies strictly on replacing standard
                characters with their stylized Unicode equivalents in real-time,
                you never have to worry about compatibility issues. Paste your
                results directly into fields that typically do not allow
                rich-text formatting—including the Instagram bio section,
                Twitter/X display names, Discord server rules, TikTok video
                descriptions, or even WhatsApp statuses. Your uniquely formatted
                text moves seamlessly wherever you copy it, preserving its exact
                aesthetic on the receiving end.
              </p>
            </div>
          </div>
        </div>

        <div className="p-6 md:p-8 bg-[#0c0c0c] border border-white/5 rounded-2xl relative overflow-hidden">
          <div className="absolute inset-0 opacity-30 pointer-events-none bg-[radial-gradient(circle_at_100%_0%,rgba(57,255,20,0.05)_0%,transparent_50%)]" />
          <div className="relative z-10">
            <h2 className="text-xl md:text-2xl font-black uppercase tracking-tighter mb-4 text-white">
              Unicode vs. ASCII: A Technical Breakdown
            </h2>
            <div className="prose prose-invert max-w-none text-white/60 text-sm md:text-base leading-relaxed space-y-4 font-mono">
              <p>
                To fully understand how the <strong>{tool.name}</strong> works,
                it is important to distinguish between standard typography and
                Unicode rendering. A traditional font is essentially an external
                styling file (like a .TTF or .OTF) that tells your computer how
                to physically draw a standard letter. If you copy text styled by
                a traditional font and paste it into Instagram, it immediately
                reverts to Instagram's default styling because the external
                styling file does not transfer with the core text.
              </p>
              <p>
                Our <strong>{category.name}</strong> generator entirely
                circumvents this limitation by utilizing the international
                Unicode standard database. Over the decades, development
                organizations have mapped tens of thousands of unique
                characters, aesthetic symbols, and mathematical alphabetic
                variations to specific numerical codes. When our script
                processes your input, it isn't simply changing the "font"—it is
                programmatically mapping and swapping your standard ASCII
                characters for entirely different mathematical or symbolic
                letters that inherently look stylish and stay formatted wherever
                you paste them.
              </p>
            </div>
          </div>
        </div>

        <div className="p-6 md:p-8 bg-[#0c0c0c] border border-white/5 rounded-2xl relative overflow-hidden">
          <div className="absolute inset-0 opacity-30 pointer-events-none bg-[radial-gradient(circle_at_100%_0%,rgba(57,255,20,0.05)_0%,transparent_50%)]" />
          <div className="relative z-10">
            <h2 className="text-xl md:text-2xl font-black uppercase tracking-tighter mb-4 text-white">
              Privacy, Performance, and Security
            </h2>
            <div className="prose prose-invert max-w-none text-white/60 text-sm md:text-base leading-relaxed space-y-4 font-mono">
              <p>
                Performance and data privacy are foundational to the
                architecture of our <strong>{category.name}</strong> utilities.
                The <strong>{tool.name}</strong> operates strictly on a
                client-side processing model. This means that every single
                keystroke, transformation, and customized configuration occurs
                entirely locally within your browser's memory. No text inputs
                are ever logged, tracked, transmitted, or saved to any external
                database or remote server.
              </p>
              <p>
                By eliminating server round-trips from the text-generation
                process, the tool is able to offer instantaneous, zero-latency
                visual feedback. You can paste thousands of words into the input
                field and see the conversion happen in real-time without
                experiencing any lag or loading screens. This powerful local
                execution ensures that you maintain absolute control over your
                digital content while enjoying an exceptionally fast and
                responsive user experience.
              </p>
            </div>
          </div>
        </div>

        <div className="p-6 md:p-8 bg-[#0c0c0c] border border-white/5 rounded-2xl relative overflow-hidden">
          <div className="absolute inset-0 opacity-30 pointer-events-none bg-[radial-gradient(circle_at_0%_100%,rgba(57,255,20,0.05)_0%,transparent_50%)]" />
          <div className="relative z-10">
            <h2 className="text-xl md:text-2xl font-black uppercase tracking-tighter mb-4 text-white">
              Accessibility and Ethical Usage of Stylized Text
            </h2>
            <div className="prose prose-invert max-w-none text-white/60 text-sm md:text-base leading-relaxed space-y-4 font-mono">
              <p>
                While the <strong>{tool.name}</strong> offers incredible
                creative potential, we advocate for responsible usage of
                stylized Unicode. Screen readers and other assistive
                technologies may interpret symbolic alphabets differently than
                standard ASCII characters. To ensure your content remains
                accessible to all users, we recommend using stylized text for
                emphasis, branding, and decorative elements rather than for
                essential informational text.
              </p>
              <p>
                Integrating <strong>{category.name}</strong> styles into your
                digital strategy should be done with an understanding of your
                audience's technical environment. Our tools are built to be
                lightweight and high-performing, but the ultimate impact of your
                design depends on how you balance aesthetic originality with
                functional clarity. By following these best practices, you can
                create a memorable digital presence that is both visually
                stunning and universally readable.
              </p>
            </div>
          </div>
        </div>

        <div className="p-6 md:p-8 bg-[#0c0c0c] border border-white/5 rounded-2xl relative overflow-hidden">
          <div className="absolute inset-0 opacity-30 pointer-events-none bg-[radial-gradient(circle_at_0%_100%,rgba(57,255,20,0.05)_0%,transparent_50%)]" />
          <div className="relative z-10">
            <h2 className="text-xl md:text-2xl font-black uppercase tracking-tighter mb-4 text-white">
              Technical Glossary: Unicode and Typographic Terms
            </h2>
            <div className="prose prose-invert max-w-none text-white/60 text-sm md:text-base leading-relaxed font-mono">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-4 text-xs">
                <p>
                  <strong>Unicode Transformation:</strong> The process of
                  programmatically mapping standard characters into specialized
                  symbolic blocks.
                </p>
                <p>
                  <strong>ASCII Standards:</strong> The original 128-character
                  set used in early computing, which forms the basis for modern
                  English typing.
                </p>
                <p>
                  <strong>Mathematical Alphanumeric Symbols:</strong> A specific
                  Unicode block containing stylized letters and numbers intended
                  for scientific notation.
                </p>
                <p>
                  <strong>Character Payload:</strong> The actual data size of a
                  string of text, which remains consistent even when stylized
                  Unicode is used.
                </p>
                <p>
                  <strong>Cross-Platform Consistency:</strong> The ability of a
                  text string to render identically across different operating
                  systems and apps.
                </p>
                <p>
                  <strong>Aesthetic Normalization:</strong> The process of
                  ensuring that stylized characters maintain proper horizontal
                  and vertical alignment.
                </p>
                <p>
                  <strong>Visual Pattern Disruption:</strong> A psychological
                  concept where non-standard elements force the brain to pause
                  and focus for longer.
                </p>
                <p>
                  <strong>Client-side Processing:</strong> Code execution that
                  happens entirely inside the user's browser without contacting
                  a server.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="space-y-10">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 bg-[#0c0c0c] border border-white/10 rounded-xl flex items-center justify-center text-accent-glitch">
            <Info className="w-6 h-6" />
          </div>
          <h2 className="text-2xl md:text-3xl font-black uppercase tracking-tighter text-center text-white">
            Frequently Asked{" "}
            <span className="text-accent-glitch">Questions</span>
          </h2>
          <p className="text-white/30 font-mono text-xs uppercase tracking-widest">
            Common queries answered
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {faqs.map((faq, i) => (
            <div
              key={i}
              className="p-5 md:p-6 bg-[#0c0c0c] border border-white/5 rounded-xl group hover:border-accent-glitch/20 transition-all duration-500 relative overflow-hidden"
            >
              <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none bg-[radial-gradient(circle_at_50%_0%,rgba(57,255,20,0.02)_0%,transparent_70%)]" />
              <div className="relative z-10">
                <h4 className="text-[11px] md:text-xs font-mono font-black text-accent-glitch uppercase tracking-wider mb-4 flex items-start gap-3">
                  <span className="inline-flex items-center justify-center w-6 h-6 bg-accent-glitch/10 border border-accent-glitch/20 rounded-md text-[9px] text-accent-glitch shrink-0 mt-0.5">
                    Q
                  </span>
                  <span className="pt-1">{faq.q}</span>
                </h4>
                <div className="flex gap-3 ml-9">
                  <p className="text-white/50 font-mono text-[12px] md:text-[13px] leading-[1.8] group-hover:text-white/70 transition-colors duration-500">
                    {faq.a}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
