import React from "react";
import { SITE_URL } from "@/lib/config";
import { Metadata } from "next";
import BackgroundEffect from "@/components/CanvasEffect";
import Link from "next/link";
import {
  Home,
  ChevronRight,
  FileText,
  CheckCircle2,
  AlertTriangle,
  Scale,
  ShieldCheck,
  Ban,
  ArrowRight,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | Legal Agreement for Using TypeWarp",
  description:
    "Read our Terms of Service to understand the legal agreement and rules for using the TypeWarp platform, including our cursed text and glitch font generators.",
  keywords: [
    "typewarp terms",
    "terms of service",
    "user agreement",
    "text generator terms",
    "usage policy",
  ],
  openGraph: {
    title: "Terms of Service | TypeWarp",
    description:
      "Read our terms of service to understand how you can use TypeWarp's free text tools.",
    url: `${SITE_URL}/terms`,
    type: "website",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "TypeWarp Terms of Service",
      },
    ],
    siteName: "TypeWarp",
  },
  twitter: {
    card: "summary_large_image",
    title: "Terms of Service | TypeWarp",
    description:
      "Read our terms of service to understand how you can use TypeWarp tools.",
    creator: "@typewarp",
    images: ["/og-image.png"],
  },
  alternates: { canonical: `${SITE_URL}/terms` },
};

const sections = [
  {
    icon: CheckCircle2,
    title: "Acceptance of Terms",
    content:
      "By accessing and using TypeWarp, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use the service. Continued use of TypeWarp constitutes acceptance of any updates or modifications to these terms.",
  },
  {
    icon: FileText,
    title: "Description of Service",
    content:
      'TypeWarp provides free text transformation tools, including font generators, translators, and stylization utilities. All tools process text locally in your browser using Unicode character mappings. The service is provided "as is" without warranties of any kind.',
  },
  {
    icon: Ban,
    title: "User Conduct",
    content:
      "You agree to use TypeWarp only for lawful purposes. You may not use the output generated by TypeWarp for harassment, hate speech, spam, phishing, or any illegal activities. You are solely responsible for how you use the transformed text.",
  },
  {
    icon: Scale,
    title: "Intellectual Property",
    content:
      "The design, code, and architecture of TypeWarp are our intellectual property. The text transformations use standard Unicode characters which are freely available. You retain full ownership of any text you input and the resulting output.",
  },
  {
    icon: ShieldCheck,
    title: "Privacy & Data",
    content:
      "All text processing happens entirely in your browser. We do not collect, store, or transmit the content of your text transformations. For full details on data handling, please refer to our Privacy Policy.",
  },
  {
    icon: AlertTriangle,
    title: "Limitation of Liability",
    content:
      "TypeWarp is not liable for any damages arising from the use or inability to use our services. We do not guarantee 100% uptime or compatibility across all platforms. Some Unicode characters may not render correctly on older devices or systems.",
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-24 lg:pt-28 pb-16 sm:pb-20 bg-bg-void text-text-primary relative overflow-hidden">
      <BackgroundEffect />

      <div className="mx-auto px-4 sm:px-6 max-w-4xl relative z-10">
        {/* Breadcrumbs */}
        <nav className="flex items-center gap-2 mb-4 lg:mb-6 font-mono text-[10px] sm:text-xs uppercase tracking-[0.2em] text-text-muted">
          <Link
            href="/"
            className="hover:text-accent-glitch transition-colors flex items-center gap-1.5"
          >
            <Home className="w-3 h-3 sm:w-3.5 sm:h-3.5" />
            Home
          </Link>
          <ChevronRight className="w-3 h-3 opacity-30" />
          <span className="text-accent-glitch">Terms</span>
        </nav>

        {/* Hero */}
        <section className="mb-12 sm:mb-16">
          <div className="inline-block px-4 py-1.5 mb-5 sm:mb-6 bg-accent-glitch/10 border border-accent-glitch/20 rounded-full text-accent-glitch text-[10px] sm:text-[11px] font-mono font-black uppercase tracking-[0.3em]">
            Legal
          </div>

          <h1 className="text-4xl sm:text-5xl md:text-6xl font-black mb-4 sm:mb-6 tracking-tight uppercase leading-[0.9]">
            <span className="text-white">Terms of</span>{" "}
            <span className="text-accent-glitch">Service.</span>
          </h1>

          <p className="text-text-muted text-sm sm:text-base md:text-lg max-w-2xl leading-relaxed">
            Please read these terms carefully before using TypeWarp. By using
            our platform, you agree to these conditions.
          </p>
        </section>

        {/* Sections */}
        <div className="space-y-4 sm:space-y-5 mb-12 sm:mb-16">
          {sections.map((section, index) => (
            <div
              key={section.title}
              className="group p-5 sm:p-6 md:p-8 bg-bg-card border border-white/[0.06] rounded-2xl hover:border-accent-glitch/25 transition-all duration-300 relative overflow-hidden"
            >
              <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-accent-glitch/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />

              <div className="flex items-start gap-4 sm:gap-5">
                <div className="p-2.5 sm:p-3 bg-white/[0.04] rounded-xl group-hover:bg-accent-glitch/10 transition-colors shrink-0">
                  <section.icon className="w-5 h-5 sm:w-6 sm:h-6 text-accent-glitch" />
                </div>

                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-3 mb-2 sm:mb-3">
                    <span className="text-[10px] sm:text-xs font-mono text-accent-glitch/50 font-bold">
                      {String(index + 1).padStart(2, "0")}
                    </span>
                    <h2 className="text-sm sm:text-base md:text-lg font-bold text-white uppercase tracking-wide group-hover:text-accent-glitch transition-colors">
                      {section.title}
                    </h2>
                  </div>
                  <p className="text-xs sm:text-sm text-text-muted leading-relaxed">
                    {section.content}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer Info */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-5 sm:p-6 bg-bg-card border border-white/[0.06] rounded-2xl">
          <div>
            <p className="text-[10px] sm:text-xs font-mono text-text-muted uppercase tracking-widest mb-1">
              Last Updated
            </p>
            <p className="text-sm sm:text-base font-bold text-white">
              February 10, 2026
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Link
              href="/privacy"
              className="inline-flex items-center gap-2 px-4 py-2 bg-white/[0.04] border border-white/[0.1] text-white font-bold text-[10px] sm:text-xs uppercase tracking-widest rounded-xl hover:border-accent-glitch/30 hover:bg-accent-glitch/5 transition-all duration-300"
            >
              Privacy Policy
              <ArrowRight className="w-3 h-3" />
            </Link>
            <Link
              href="/cookies"
              className="inline-flex items-center gap-2 px-4 py-2 bg-white/[0.04] border border-white/[0.1] text-white font-bold text-[10px] sm:text-xs uppercase tracking-widest rounded-xl hover:border-accent-glitch/30 hover:bg-accent-glitch/5 transition-all duration-300"
            >
              Cookies
              <ArrowRight className="w-3 h-3" />
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
