import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | TypeWarp",
  description:
    "Read our terms of service to understand how you can use TypeWarp.",
  alternates: {
    canonical: "https://typewarp.com/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-32 pb-20 px-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl md:text-6xl font-black mb-8 text-[var(--foreground)]">
          Terms of <span className="text-red-500 italic">Service</span>
        </h1>
        <div className="prose prose-invert prose-red max-w-none space-y-8 text-[var(--muted)]">
          <section>
            <h2 className="text-2xl font-bold text-[var(--foreground)]">
              1. Acceptance of Terms
            </h2>
            <p className="text-lg leading-relaxed">
              By accessing and using TypeWarp ("the Website"), you agree to be
              bound by these Terms of Service. If you do not agree with any part
              of these terms, you must not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[var(--foreground)]">
              2. Description of Service
            </h2>
            <p className="text-lg leading-relaxed">
              TypeWarp provides various text transformation tools, including
              font generators, translators, and stylization tools. These
              services are provided "as is" and for creative/entertainment
              purposes only.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[var(--foreground)]">
              3. User Conduct
            </h2>
            <p className="text-lg leading-relaxed">
              You agree to use the Website only for lawful purposes. You are
              prohibited from using the output generated by TypeWarp for
              harassment, hate speech, or any illegal activities.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[var(--foreground)]">
              4. Intellectual Property
            </h2>
            <p className="text-lg leading-relaxed">
              The design, code, and original content of TypeWarp are our
              intellectual property. The text transformations provided use
              standard Unicode characters; however, the specific implementation
              and toolsets are unique to our platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-[var(--foreground)]">
              5. Limitation of Liability
            </h2>
            <p className="text-lg leading-relaxed">
              TypeWarp is not liable for any damages arising out of the use or
              inability to use the services offered. We do not guarantee 100%
              uptime or compatibility across all legacy devices.
            </p>
          </section>

          <section>
            <p className="text-sm border-t border-[var(--card-border)] pt-8">
              Last Updated: February 5, 2026
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
